### ISSUE TITLE
Failed to validate signature when absolute callback url is used.

### ISSUE THREAD

**Issue by paragasu** [MJMortimer/elixero#9]
Setting the callback_url to any valid url eg: `http://localhost` will give out `Failed to validate signature`. But setting it to `localhost` or empty string  works.

`%{"http_status_code" => 401, "oauth_problem" => "signature_invalid", "oauth_problem_advice" => "Failed to validate signature"}`

Example of failed request as generated from `EliXero.Utils.Oauth.create_auth_header` call.

`"OAuth oauth_signature=\"BYZbLxRCXG7VC%2BUcV8BLgKYzJE4%3D\", oauth_callback=\"http://localhost\", oauth_consumer_key=\"IWF2TM6LCD0EHEKCOX6O6SI9KMO2GL\", oauth_nonce=\"kZ2dCE8r1S\", oauth_signature_method=\"HMAC-SHA1\", oauth_version=\"1.0\", oauth_timestamp=\"1498365910\""`

**Comment by MJMortimer** [comment]
Hey @paragasu, this will no doubt be due to character escape and url encoding for the oauth signature. I'll take a look at this for you

**Comment by MJMortimer** [comment]
@paragasu This should be resolved in #10 

Can you please give it a try and let me know how you get on?

**Comment by paragasu** [comment]
@MJMortimer appreciate your quick reply. I confirm the commit works now. Thank you.

**Comment by MJMortimer** [comment]
@paragasu Will you be open sourcing your project that uses EliXero? I'd love to see what you build with it

**Comment by paragasu** [comment]
@MJMortimer I am currently doing a xero tax reporting plugin for an accounting firm in Malaysia. I will love to opensource it but i think the company is not very keen on that idea.
